name: build

on: 
  push:
    branches:
    - "*"
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        target: [XY-C1]
    steps:
      - uses: actions/checkout@v3
      - uses: hendrikmuhs/ccache-action@v1.2
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18.6'
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-v1
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Prepare
        run: |
          sudo apt update
          sudo apt install libtool-bin gperf python3-docutils autopoint gettext ccache
          # https://github.com/actions/setup-go/issues/107
          echo "${GOROOT}/bin" >> $GITHUB_PATH
      - name: Build
        run: |
          make ${{ matrix.target }}
          if [ "${{ matrix.target }}" = "K2P-NANO" ]; then
            image=$(ls trunk/images/*.trx)
            mv $image $(echo $image | sed 's/K2P/K2P-NANO/')
          fi
          echo "TAG_ANME=$(date +%Y%m%d)" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v3
        with:
          name: images
          path: trunk/images/*.trx
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ env.TAG_ANME }}
          force_push_tag: true
      - uses: ncipollo/release-action@v1
        with:
          commit: ${{ github.sha }}
          tag: ${{ env.TAG_ANME }}
          artifacts: trunk/images/*.trx
          allowUpdates: true
